#!/bin/bash

#preinstall file


sudo apt-get update
sudo apt-get install postgresql postgresql-contrib
sudo -u postgres createuser --interactive
sudo -u postgres createdb new1db
sudo adduser new1db
sudo apt install postgresql-client-common
#sudo -u newdb psql
#new db < pgre.sql
#\du+


exit
