#!/bin/bash

#preinstall file


sudo apt update
sudo apt install postgresql postgresql-contrib
sudo -u postgres createuser --interactive
sudo -u postgres createdb newdb
sudo adduser newdb
sudo -u newdb psql
new db < pgre.sql
\d

exit
